version: '3.8'

services:
  app:
    build: .
    container_name: url_shortener
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./migrations:/app/migrations
      - ./templates:/app/templates
    command: >
      bash -c "
        sleep 10 &&
        sqlx migrate run &&
        cargo run --release
      "