version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: url_shortener
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    container_name: url-shortener
    depends_on:
      - mysql
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: mysql://user:password@mysql:3306/url_shortener
    volumes:
      - ./migrations:/app/migrations
      - ./templates:/app/templates
    command: >
      bash -c "
        sleep 10 &&
        sqlx migrate run &&
        cargo run --release
      "

volumes:
  mysql_data:
