version: '3.8'

services:
  mysql:
    image: mysql:8.0.41-debian
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: url-shortener

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  app:
    build: .
    container_name: url_shortener
    depends_on:
      - mysql
      - redis
    restart: on-failure
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./migrations:/app/migrations
      - ./templates:/app/templates
    command: >
      bash -c "
        sleep 15 &&
        sqlx migrate run &&
        ./url_shortener
      "